AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'storage: container storage, a @wolfeidau template'

Parameters:
  AppName:
    Type: String
    Description: The name of the application.

  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: "dev"

  Branch:
    Type: String
    Default: "master"

Outputs:
  RepositoryArn:
    Description: "Repository ARN"
    Value: !GetAtt Repository.Arn
  RepositoryUri:
    Description: "Repository URI"
    Value: !GetAtt Repository.RepositoryUri

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${AppName}_${Stage}_${Branch}"